spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_sosial?useSSL=false
    username: root
    password: welcome1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: or.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:

              - email
              - public_profile



app:
